ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_118', 'oakmont-country-club', 'Oakmont Country Club (Oakmont, PA)', 'Golf & Country Club', 'Marc', 'Stevenson', 'mstevenson@oakmontcc.org', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Oakmont, PA. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_119', 'merion-golf-club', 'Merion Golf Club (Ardmore, PA)', 'Golf & Country Club', 'Paul', 'Levy', 'plevy@meriongolfclub.com', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Ardmore, PA. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_120', 'aronomink-golf-club', 'Aronomink Golf Club (Newtown Square, PA)', 'Golf & Country Club', 'Stephen', 'Strockis', 'sstrockis@aronimink.org', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Newtown Square, PA. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_121', 'the-philadelphia-cricket-club', 'The Philadelphia Cricket Club (Philadelphia, PA)', 'Golf & Cricket Club', 'Timothy', 'Muessle', 'tmuessle@philacricket.com', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Philadelphia, PA. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_122', 'the-union-league-of-philadelphia', 'The Union League of Philadelphia (Philadelphia, PA)', 'City & Country Club', 'Jeffrey', 'McFadden', 'jmcfadden@unionleague.org', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Philadelphia, PA. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_123', 'muirfield-village-golf-club', 'Muirfield Village Golf Club (Dublin, OH)', 'Golf & Country Club', 'Nicholas', 'LaRocca', 'nlarocca@mvgc.org', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Dublin, OH. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_124', 'inverness-club', 'Inverness Club (Toledo, OH)', 'Golf & Country Club', 'John', 'Koster', 'jkoster@invernessclub.com', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Toledo, OH. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;
INSERT INTO sales_leads (id, lead_code, club_name, organization_type, contact_first_name, contact_last_name, contact_email, first_seen_at, last_seen_at, status, clicks_count, notes)
VALUES ('lead_na_125', 'the-camargo-club', 'The Camargo Club (Cincinnati, OH)', 'Golf & Country Club', 'Michael', 'Ginn', 'mginn@camargoclub.org', '2026-08-09T14:32:00.000Z', '2026-08-09T14:32:00.000Z', 'new', 0, 'Target Role: General Manager in Cincinnati, OH. Sourced for North America Private Club Outreach.')
ON CONFLICT(contact_email, club_name) DO UPDATE SET last_seen_at = excluded.last_seen_at;