-- Migration 016: Sync Sent Emails into Lead Tracker & Suppression List with Zero Duplicates

-- 1. Insert/Update Organizations
INSERT OR IGNORE INTO leads_organizations (id, name, organization_type, country, region, created_at, updated_at) VALUES
('org_pinehurst', 'Pinehurst Country Club', 'golf_country_club', 'US', 'NC', datetime('now'), datetime('now')),
('org_greenwood', 'Greenwood Country Club', 'golf_country_club', 'US', 'SC', datetime('now'), datetime('now')),
('org_lexington', 'Lexington Country Club', 'golf_country_club', 'US', 'FL', datetime('now'), datetime('now')),
('org_quailcreek', 'Quail Creek Country Club', 'golf_country_club', 'US', 'FL', datetime('now'), datetime('now')),
('org_sevenoaks', 'Seven Oaks Country Club', 'golf_country_club', 'US', 'PA', datetime('now'), datetime('now')),
('org_battleground', 'Battleground Country Club', 'golf_country_club', 'US', 'NJ', datetime('now'), datetime('now')),
('org_chikaming', 'Chikaming Country Club', 'golf_country_club', 'US', 'MI', datetime('now'), datetime('now')),
('org_winchester', 'Winchester Country Club', 'golf_country_club', 'US', 'MA', datetime('now'), datetime('now')),
('org_moorhead', 'Moorhead Country Club', 'golf_country_club', 'US', 'MN', datetime('now'), datetime('now')),
('org_houston_yc', 'Houston Yacht Club', 'yacht_club', 'US', 'TX', datetime('now'), datetime('now')),
('org_hawthorns', 'The Hawthorns Golf & Country Club', 'golf_country_club', 'US', 'IN', datetime('now'), datetime('now')),
('org_stcharles_yc', 'St. Charles Yacht Club', 'yacht_club', 'US', 'FL', datetime('now'), datetime('now')),
('org_brookfield', 'Brookfield Country Club', 'golf_country_club', 'US', 'NY', datetime('now'), datetime('now')),
('org_guilford_yc', 'Guilford Yacht Club', 'yacht_club', 'US', 'CT', datetime('now'), datetime('now')),
('org_richmondhill_curling', 'Richmond Hill Curling Club', 'curling_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_chartiers', 'Chartiers Country Club', 'golf_country_club', 'US', 'PA', datetime('now'), datetime('now')),
('org_lubbock', 'Lubbock Country Club', 'golf_country_club', 'US', 'TX', datetime('now'), datetime('now')),
('org_leaside_curling', 'Leaside Curling Club', 'curling_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_dixie_curling', 'Dixie Curling Club', 'curling_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_coppinwood', 'Coppinwood Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_ottawa_hunt', 'Ottawa Hunt & Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_prescott', 'Prescott Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_pineview', 'Pine View Golf Course', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_camelot', 'Camelot Golf & Country Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_lookoutpoint', 'Lookout Point Country Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_haileybury', 'Haileybury Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_oakvillegolf', 'Oakville Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_portcarling', 'Port Carling Golf & Country Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_londonhunt', 'London Hunt & Country Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_pipersheath', 'Piper''s Heath Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_westhaven', 'West Haven Golf & Country Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now')),
('org_pheasantrun', 'Pheasant Run Golf Club', 'golf_country_club', 'CA', 'ON', datetime('now'), datetime('now'));

-- 2. Insert/Update Contacted Leads into leads_contacts
INSERT OR REPLACE INTO leads_contacts (id, organization_id, full_name, title, business_email, status, lead_score, created_at, updated_at) VALUES
('cnt_moriah_leger', 'org_pinehurst', 'Moriah Leger', 'Events & Member Services', 'moriah.leger@pinehurst.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_nancy_sadler', 'org_pinehurst', 'Nancy Sadler', 'Membership Manager', 'nancy.sadler@pinehurst.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_brian_meador', 'org_pinehurst', 'Brian Meador', 'Golf Operations', 'brian.meador@pinehurst.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_ben_bridgers', 'org_pinehurst', 'Ben Bridgers', 'Director of Golf', 'ben.bridgers@pinehurst.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_crystal_eva', 'org_greenwood', 'Crystal Evans', 'Membership Director', 'crystal.evans@greenwoodcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_kevin_hill', 'org_greenwood', 'Kevin Hill', 'General Manager', 'kevin.hill@greenwoodcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_ptruchan', 'org_lexington', 'Patrick Truchan', 'General Manager', 'ptruchan@lexingtoncountryclub.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_jrosenkranz', 'org_lexington', 'Jennifer Rosenkranz', 'Member Events Director', 'jrosenkranz@lexingtoncountryclub.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_ewarburton', 'org_quailcreek', 'Emme Warburton', 'Membership Manager', 'ewarburton@quailcreekcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_rvelez', 'org_sevenoaks', 'Renei Velez', 'Events Manager', 'rvelez@sevenoakscc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_curban', 'org_sevenoaks', 'Eryn Urban', 'Membership Director', 'curban@sevenoakscc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_econtreras', 'org_sevenoaks', 'Enrique Contreras', 'General Manager', 'econtreras@sevenoakscc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_vincent_san', 'org_battleground', 'Vincent Sanchez', 'Member Experience', 'vincent.sanchez@battlegroundcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_joshua_hens', 'org_battleground', 'Joshua Henson', 'General Manager', 'joshua.henson@battlegroundcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_rick_dowling', 'org_chikaming', 'Rick Dowling', 'General Manager', 'rick.dowling@chikamingcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_liz_winchester', 'org_winchester', 'Liz', 'Membership Director', 'liz@winchestercc.org', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_lillie_kirc', 'org_moorhead', 'Lillie Kirchoff', 'Events & Socials', 'lillie.kirchoff@moorheadcc.com', 'CONTACTED', 65, '2026-08-06 10:00:00', '2026-08-06 10:00:00'),
('cnt_gm_houston_yc', 'org_houston_yc', 'Ernie', 'General Manager', 'gm@houstonyachtclub.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_jkurdziel', 'org_hawthorns', 'Jeff Kurdziel', 'General Manager', 'jkurdziel@hawthornsclub.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_genmgr_stcharles', 'org_stcharles_yc', 'Justin', 'General Manager', 'genmgr@stcharlesyc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_cmelroy', 'org_brookfield', 'Cory Melroy', 'General Manager', 'cmelroy@brookfieldcc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_gm_guilford_yc', 'org_guilford_yc', 'Mark', 'General Manager', 'generalmanager@guilfordyc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_manager_richmondhill', 'org_richmondhill_curling', 'Fred', 'Club Manager', 'manager@richmondhillcurling.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_bdavis', 'org_chartiers', 'Robert Davis', 'General Manager', 'bdavis@chartierscc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_omar_lubbock', 'org_lubbock', 'Omar', 'General Manager', 'omar@lubbockcc.org', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_gm_leaside', 'org_leaside_curling', 'Paivi', 'General Manager', 'generalmanager@leasidecurling.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_gm_dixie', 'org_dixie_curling', 'Patrick', 'General Manager', 'generalmanager@dixiecurling.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_pboussiere', 'org_coppinwood', 'Paul Boussiere', 'General Manager', 'pboussiere@coppinwood.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_mpeterson', 'org_ottawa_hunt', 'Marc Peterson', 'General Manager', 'mpeterson@ottawahuntclub.org', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_pgc_prescott', 'org_prescott', 'Steve', 'General Manager', 'pgc@prescottgolfclub.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_mike_pineview', 'org_pineview', 'Mike', 'General Manager', 'mike@pineview.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_grichardson_camelot', 'org_camelot', 'Greg Richardson', 'General Manager', 'grichardson@camelotgcc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_rob_lookoutpoint', 'org_lookoutpoint', 'Rob', 'General Manager', 'rob@lookoutpoint.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_taylor_haileybury', 'org_haileybury', 'Taylor', 'General Manager', 'taylor@haileyburygolf.ca', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_info_oakvillegolf', 'org_oakvillegolf', 'Scott', 'General Manager', 'info@oakvillegolfclub.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_rennis', 'org_portcarling', 'Ryan Ennis', 'General Manager', 'rennis@portcarlinggc.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_info_londonhunt', 'org_londonhunt', 'Jon', 'General Manager', 'info@londonhuntclub.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_marc_pipersheath', 'org_pipersheath', 'Marc', 'General Manager', 'marc@pipersheath.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_gm_westhaven', 'org_westhaven', 'Jeff', 'General Manager', 'gm@westhavengolf.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00'),
('cnt_rob_pheasantrun', 'org_pheasantrun', 'Robert', 'General Manager', 'rob@pheasantrungolf.com', 'CONTACTED', 65, '2026-08-04 10:00:00', '2026-08-04 10:00:00');

-- 3. Seed into suppression_list to guarantee NO duplicates or repeat emails
INSERT OR IGNORE INTO suppression_list (email, reason, source_campaign, suppressed_at) VALUES
('moriah.leger@pinehurst.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('nancy.sadler@pinehurst.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('brian.meador@pinehurst.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('ben.bridgers@pinehurst.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('crystal.evans@greenwoodcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('kevin.hill@greenwoodcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('ptruchan@lexingtoncountryclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('jrosenkranz@lexingtoncountryclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('ewarburton@quailcreekcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('rvelez@sevenoakscc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('curban@sevenoakscc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('econtreras@sevenoakscc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('vincent.sanchez@battlegroundcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('joshua.henson@battlegroundcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('rick.dowling@chikamingcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('liz@winchestercc.org', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('lillie.kirchoff@moorheadcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 6', datetime('now')),
('gm@houstonyachtclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('jkurdziel@hawthornsclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('genmgr@stcharlesyc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('cmelroy@brookfieldcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('generalmanager@guilfordyc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('manager@richmondhillcurling.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('bdavis@chartierscc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('omar@lubbockcc.org', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('generalmanager@leasidecurling.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('generalmanager@dixiecurling.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('pboussiere@coppinwood.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('mpeterson@ottawahuntclub.org', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('pgc@prescottgolfclub.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('mike@pineview.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('grichardson@camelotgcc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('rob@lookoutpoint.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('taylor@haileyburygolf.ca', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('info@oakvillegolfclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('rennis@portcarlinggc.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('info@londonhuntclub.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('marc@pipersheath.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('gm@westhavengolf.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now')),
('rob@pheasantrungolf.com', 'ALREADY_CONTACTED_BY_MAYANK', 'Manual Gmail Campaign Aug 4', datetime('now'));
